name: Noor Navillus / Noor Sullivan
favicon: null
layout_spectrum: 0.38753
typography_spectrum: 0.44623
title: Noor Navillus / Noor Sullivan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#92c4f9'
    - '#15191a'
    - '#565a5b'
    - '#a48f7a'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
